import esbuild from "esbuild";
import { copyFile, mkdir } from "node:fs/promises";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/johanmensah/ripple
*/
`;

const prod = process.argv[2] === "production";

// The dev vault gets copies of the built artefacts, never a symlink to the
// repo: the repo contains the dev vault, so a symlink recurses forever.
const vaultPluginDir = "dev-vault/.obsidian/plugins/ripple";
const copyToVault = {
	name: "copy-to-vault",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;
			await mkdir(vaultPluginDir, { recursive: true });
			for (const file of ["main.js", "manifest.json", "styles.css"]) {
				await copyFile(file, `${vaultPluginDir}/${file}`).catch(() => undefined);
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	jsx: "automatic",
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	minify: prod,
	plugins: [copyToVault],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
